language: csharp

mono: none
dotnet: 5.0.103
    
env:
    - SOLUTION: HW1/BWTAlgorithm/BWTAlgorithm.sln
    - SOLUTION: HW1/SortingArray/SortingArray.sln
    - SOLUTION: HW2/LZWProgram/LZWProgram.sln
    - SOLUTION: HW2/StackCalc/StackCalc.sln
    - SOLUTION: HW3/BTreeImplementation/BTreeImplementation.sln
    - SOLUTION: HW4/ArithmeticTree/ArithmeticTree.sln
    - SOLUTION: HW4/UniqueList/UniqueList.sln
    - SOLUTION: HW5/StackCalc/StackCalc.sln
    
script:
    - dotnet test $SOLUTION
