image: Visual Studio 2019

environment:
  matrix:
      - SOLUTION: HW1/BWTAlgorithm/BWTAlgorithm.sln
      - SOLUTION: HW1/SortingArray/SortingArray.sln

before_build:
    - nuget restore %SOLUTION%
    
build:
    project: %SOLUTION%
    
test_script:
    - dotnet test %SOLUTION%
